// <auto-generated />
using System;
using EWMS.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EWMS.Migrations
{
    [DbContext(typeof(EWMSDbContext))]
    [Migration("20260307133818_TransferLocationUpdate")]
    partial class TransferLocationUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EWMS.Models.ActivityLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LogID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Ipaddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("IPAddress");

                    b.Property<int?>("RecordId")
                        .HasColumnType("int")
                        .HasColumnName("RecordID");

                    b.Property<string>("TableName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("LogId")
                        .HasName("PK__Activity__5E5499A88A4A1BD6");

                    b.HasIndex("UserId");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("EWMS.Models.Inventory", b =>
                {
                    b.Property<int>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("InventoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InventoryId"));

                    b.Property<DateTime?>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("LocationId")
                        .HasColumnType("int")
                        .HasColumnName("LocationID");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    b.Property<int?>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("InventoryId")
                        .HasName("PK__Inventor__F5FDE6D30AD3E968");

                    b.HasIndex(new[] { "LocationId" }, "IX_Inventory_LocationID");

                    b.HasIndex(new[] { "ProductId" }, "IX_Inventory_ProductID");

                    b.HasIndex(new[] { "ProductId", "LocationId" }, "UQ_Product_Location")
                        .IsUnique();

                    b.ToTable("Inventory");
                });

            modelBuilder.Entity("EWMS.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LocationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<int>("Capacity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(200)
                        .HasColumnName("Capacity");

                    b.Property<string>("LocationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LocationName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Rack")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int")
                        .HasColumnName("WarehouseID");

                    b.HasKey("LocationId")
                        .HasName("PK__Location__E7FEA477B3648E27");

                    b.HasIndex(new[] { "WarehouseId", "LocationCode" }, "UQ_Location_Code")
                        .IsUnique();

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("EWMS.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    b.Property<decimal?>("CostPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal?>("SellingPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ProductId")
                        .HasName("PK__Products__B40CC6ED0D0460B1");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("EWMS.Models.ProductCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int")
                        .HasColumnName("SupplierID");

                    b.HasKey("CategoryId")
                        .HasName("PK__ProductC__19093A2B5BEBEBCB");

                    b.HasIndex("SupplierId");

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("EWMS.Models.PurchaseOrder", b =>
                {
                    b.Property<int>("PurchaseOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PurchaseOrderID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PurchaseOrderId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Pending");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int")
                        .HasColumnName("SupplierID");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int")
                        .HasColumnName("WarehouseID");

                    b.HasKey("PurchaseOrderId")
                        .HasName("PK__Purchase__036BAC44907DB00F");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("SupplierId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("PurchaseOrders");
                });

            modelBuilder.Entity("EWMS.Models.PurchaseOrderDetail", b =>
                {
                    b.Property<int>("PurchaseOrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PurchaseOrderDetailID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PurchaseOrderDetailId"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("int")
                        .HasColumnName("PurchaseOrderID");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalPrice")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(29, 2)")
                        .HasComputedColumnSql("([Quantity]*[UnitPrice])", true);

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("PurchaseOrderDetailId")
                        .HasName("PK__Purchase__5026B6F8F3DE3DF8");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("PurchaseOrderDetails");
                });

            modelBuilder.Entity("EWMS.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__8AFACE3A46CFC6C0");

                    b.HasIndex(new[] { "RoleName" }, "UQ__Roles__8A2B6160D5861D69")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("EWMS.Models.SalesOrder", b =>
                {
                    b.Property<int>("SalesOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SalesOrderID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalesOrderId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CustomerAddress")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CustomerPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Pending");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int")
                        .HasColumnName("WarehouseID");

                    b.HasKey("SalesOrderId")
                        .HasName("PK__SalesOrd__B14003C20855141B");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("WarehouseId");

                    b.ToTable("SalesOrders");
                });

            modelBuilder.Entity("EWMS.Models.SalesOrderDetail", b =>
                {
                    b.Property<int>("SalesOrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SalesOrderDetailID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalesOrderDetailId"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SalesOrderId")
                        .HasColumnType("int")
                        .HasColumnName("SalesOrderID");

                    b.Property<decimal?>("TotalPrice")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(29, 2)")
                        .HasComputedColumnSql("([Quantity]*[UnitPrice])", true);

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("SalesOrderDetailId")
                        .HasName("PK__SalesOrd__6B9B5105283D350A");

                    b.HasIndex("ProductId");

                    b.HasIndex("SalesOrderId");

                    b.ToTable("SalesOrderDetails");
                });

            modelBuilder.Entity("EWMS.Models.StockInDetail", b =>
                {
                    b.Property<int>("StockInDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StockInDetailID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StockInDetailId"));

                    b.Property<int>("LocationId")
                        .HasColumnType("int")
                        .HasColumnName("LocationID");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("StockInId")
                        .HasColumnType("int")
                        .HasColumnName("StockInID");

                    b.Property<decimal?>("TotalPrice")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(29, 2)")
                        .HasComputedColumnSql("([Quantity]*[UnitPrice])", true);

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("StockInDetailId")
                        .HasName("PK__StockInD__EEDA10336BCA716C");

                    b.HasIndex("LocationId");

                    b.HasIndex("ProductId");

                    b.HasIndex(new[] { "StockInId" }, "IX_StockInDetails_StockInID");

                    b.ToTable("StockInDetails");
                });

            modelBuilder.Entity("EWMS.Models.StockInReceipt", b =>
                {
                    b.Property<int>("StockInId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StockInID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StockInId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("PurchaseOrderId")
                        .HasColumnType("int")
                        .HasColumnName("PurchaseOrderID");

                    b.Property<string>("Reason")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("ReceivedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReceivedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("TotalAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<int?>("TransferId")
                        .HasColumnType("int")
                        .HasColumnName("TransferID");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int")
                        .HasColumnName("WarehouseID");

                    b.HasKey("StockInId")
                        .HasName("PK__StockInR__794DA64C972DD569");

                    b.HasIndex("PurchaseOrderId");

                    b.HasIndex("ReceivedBy");

                    b.HasIndex("TransferId");

                    b.HasIndex(new[] { "WarehouseId", "ReceivedDate" }, "IX_StockInReceipts_WarehouseID_Date");

                    b.ToTable("StockInReceipts");
                });

            modelBuilder.Entity("EWMS.Models.StockOutDetail", b =>
                {
                    b.Property<int>("StockOutDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StockOutDetailID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StockOutDetailId"));

                    b.Property<int>("LocationId")
                        .HasColumnType("int")
                        .HasColumnName("LocationID");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("StockOutId")
                        .HasColumnType("int")
                        .HasColumnName("StockOutID");

                    b.Property<decimal?>("TotalPrice")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(29, 2)")
                        .HasComputedColumnSql("([Quantity]*[UnitPrice])", true);

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("StockOutDetailId")
                        .HasName("PK__StockOut__EB248EFFF2BB9B54");

                    b.HasIndex("LocationId");

                    b.HasIndex("ProductId");

                    b.HasIndex(new[] { "StockOutId" }, "IX_StockOutDetails_StockOutID");

                    b.ToTable("StockOutDetails");
                });

            modelBuilder.Entity("EWMS.Models.StockOutReceipt", b =>
                {
                    b.Property<int>("StockOutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StockOutID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StockOutId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IssuedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("IssuedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Reason")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("SalesOrderId")
                        .HasColumnType("int")
                        .HasColumnName("SalesOrderID");

                    b.Property<decimal?>("TotalAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<int?>("TransferId")
                        .HasColumnType("int")
                        .HasColumnName("TransferID");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int")
                        .HasColumnName("WarehouseID");

                    b.HasKey("StockOutId")
                        .HasName("PK__StockOut__C5308D9ABE69A017");

                    b.HasIndex("IssuedBy");

                    b.HasIndex("SalesOrderId");

                    b.HasIndex("TransferId");

                    b.HasIndex(new[] { "WarehouseId", "IssuedDate" }, "IX_StockOutReceipts_WarehouseID_Date");

                    b.ToTable("StockOutReceipts");
                });

            modelBuilder.Entity("EWMS.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SupplierID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("SupplierId")
                        .HasName("PK__Supplier__4BE666940123C261");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("EWMS.Models.TransferDetail", b =>
                {
                    b.Property<int>("TransferDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TransferDetailID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransferDetailId"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("TransferId")
                        .HasColumnType("int")
                        .HasColumnName("TransferID");

                    b.HasKey("TransferDetailId")
                        .HasName("PK__Transfer__F9BF690FFA8A9B6C");

                    b.HasIndex("ProductId");

                    b.HasIndex("TransferId");

                    b.ToTable("TransferDetails");
                });

            modelBuilder.Entity("EWMS.Models.TransferRequest", b =>
                {
                    b.Property<int>("TransferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TransferID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransferId"));

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("FromLocationId")
                        .HasColumnType("int")
                        .HasColumnName("FromLocationID");

                    b.Property<int>("FromWarehouseId")
                        .HasColumnType("int")
                        .HasColumnName("FromWarehouseID");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RequestedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RequestedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Pending");

                    b.Property<int?>("ToLocationId")
                        .HasColumnType("int")
                        .HasColumnName("ToLocationID");

                    b.Property<int>("ToWarehouseId")
                        .HasColumnType("int")
                        .HasColumnName("ToWarehouseID");

                    b.Property<string>("TransferType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Warehouse");

                    b.HasKey("TransferId")
                        .HasName("PK__Transfer__95490171829B880B");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("FromLocationId");

                    b.HasIndex("FromWarehouseId");

                    b.HasIndex("RequestedBy");

                    b.HasIndex("ToLocationId");

                    b.HasIndex("ToWarehouseId");

                    b.ToTable("TransferRequests");
                });

            modelBuilder.Entity("EWMS.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CCACA6872C7E");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Username" }, "UQ__Users__536C85E4E1CC2CF9")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EWMS.Models.UserWarehouse", b =>
                {
                    b.Property<int>("UserWarehouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserWarehouseID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserWarehouseId"));

                    b.Property<DateTime?>("AssignedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int")
                        .HasColumnName("WarehouseID");

                    b.HasKey("UserWarehouseId")
                        .HasName("PK__UserWare__BEEFA8461CC98871");

                    b.HasIndex(new[] { "UserId" }, "IX_UserWarehouses_UserID");

                    b.HasIndex(new[] { "WarehouseId" }, "IX_UserWarehouses_WarehouseID");

                    b.HasIndex(new[] { "UserId", "WarehouseId" }, "UQ_User_Warehouse")
                        .IsUnique();

                    b.ToTable("UserWarehouses");
                });

            modelBuilder.Entity("EWMS.Models.Warehouse", b =>
                {
                    b.Property<int>("WarehouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("WarehouseID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WarehouseId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("WarehouseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("WarehouseId")
                        .HasName("PK__Warehous__2608AFD9B10411D1");

                    b.ToTable("Warehouses");
                });

            modelBuilder.Entity("EWMS.Models.ActivityLog", b =>
                {
                    b.HasOne("EWMS.Models.User", "User")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_ActivityLogs_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EWMS.Models.Inventory", b =>
                {
                    b.HasOne("EWMS.Models.Location", "Location")
                        .WithMany("Inventories")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Inventory_Locations");

                    b.HasOne("EWMS.Models.Product", "Product")
                        .WithMany("Inventories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Inventory_Products");

                    b.Navigation("Location");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EWMS.Models.Location", b =>
                {
                    b.HasOne("EWMS.Models.Warehouse", "Warehouse")
                        .WithMany("Locations")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Locations_Warehouses");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("EWMS.Models.Product", b =>
                {
                    b.HasOne("EWMS.Models.ProductCategory", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK_Products_Categories");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("EWMS.Models.ProductCategory", b =>
                {
                    b.HasOne("EWMS.Models.Supplier", "Supplier")
                        .WithMany("ProductCategories")
                        .HasForeignKey("SupplierId")
                        .HasConstraintName("FK_ProductCategories_Suppliers");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("EWMS.Models.PurchaseOrder", b =>
                {
                    b.HasOne("EWMS.Models.User", "CreatedByNavigation")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_PurchaseOrders_Users");

                    b.HasOne("EWMS.Models.Supplier", "Supplier")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("SupplierId")
                        .IsRequired()
                        .HasConstraintName("FK_PurchaseOrders_Suppliers");

                    b.HasOne("EWMS.Models.Warehouse", "Warehouse")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("WarehouseId")
                        .IsRequired()
                        .HasConstraintName("FK_PurchaseOrders_Warehouses");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Supplier");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("EWMS.Models.PurchaseOrderDetail", b =>
                {
                    b.HasOne("EWMS.Models.Product", "Product")
                        .WithMany("PurchaseOrderDetails")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_POD_Products");

                    b.HasOne("EWMS.Models.PurchaseOrder", "PurchaseOrder")
                        .WithMany("PurchaseOrderDetails")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_POD_PurchaseOrders");

                    b.Navigation("Product");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("EWMS.Models.SalesOrder", b =>
                {
                    b.HasOne("EWMS.Models.User", "CreatedByNavigation")
                        .WithMany("SalesOrders")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_SalesOrders_Users");

                    b.HasOne("EWMS.Models.Warehouse", "Warehouse")
                        .WithMany("SalesOrders")
                        .HasForeignKey("WarehouseId")
                        .IsRequired()
                        .HasConstraintName("FK_SalesOrders_Warehouses");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("EWMS.Models.SalesOrderDetail", b =>
                {
                    b.HasOne("EWMS.Models.Product", "Product")
                        .WithMany("SalesOrderDetails")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_SOD_Products");

                    b.HasOne("EWMS.Models.SalesOrder", "SalesOrder")
                        .WithMany("SalesOrderDetails")
                        .HasForeignKey("SalesOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SOD_SalesOrders");

                    b.Navigation("Product");

                    b.Navigation("SalesOrder");
                });

            modelBuilder.Entity("EWMS.Models.StockInDetail", b =>
                {
                    b.HasOne("EWMS.Models.Location", "Location")
                        .WithMany("StockInDetails")
                        .HasForeignKey("LocationId")
                        .IsRequired()
                        .HasConstraintName("FK_SID_Location");

                    b.HasOne("EWMS.Models.Product", "Product")
                        .WithMany("StockInDetails")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_SID_Product");

                    b.HasOne("EWMS.Models.StockInReceipt", "StockIn")
                        .WithMany("StockInDetails")
                        .HasForeignKey("StockInId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SID_StockIn");

                    b.Navigation("Location");

                    b.Navigation("Product");

                    b.Navigation("StockIn");
                });

            modelBuilder.Entity("EWMS.Models.StockInReceipt", b =>
                {
                    b.HasOne("EWMS.Models.PurchaseOrder", "PurchaseOrder")
                        .WithMany("StockInReceipts")
                        .HasForeignKey("PurchaseOrderId")
                        .HasConstraintName("FK_StockIn_PurchaseOrder");

                    b.HasOne("EWMS.Models.User", "ReceivedByNavigation")
                        .WithMany("StockInReceipts")
                        .HasForeignKey("ReceivedBy")
                        .IsRequired()
                        .HasConstraintName("FK_StockIn_ReceivedBy");

                    b.HasOne("EWMS.Models.TransferRequest", "Transfer")
                        .WithMany("StockInReceipts")
                        .HasForeignKey("TransferId")
                        .HasConstraintName("FK_StockIn_Transfer");

                    b.HasOne("EWMS.Models.Warehouse", "Warehouse")
                        .WithMany("StockInReceipts")
                        .HasForeignKey("WarehouseId")
                        .IsRequired()
                        .HasConstraintName("FK_StockIn_Warehouse");

                    b.Navigation("PurchaseOrder");

                    b.Navigation("ReceivedByNavigation");

                    b.Navigation("Transfer");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("EWMS.Models.StockOutDetail", b =>
                {
                    b.HasOne("EWMS.Models.Location", "Location")
                        .WithMany("StockOutDetails")
                        .HasForeignKey("LocationId")
                        .IsRequired()
                        .HasConstraintName("FK_SOD_Location");

                    b.HasOne("EWMS.Models.Product", "Product")
                        .WithMany("StockOutDetails")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_SOD_Product");

                    b.HasOne("EWMS.Models.StockOutReceipt", "StockOut")
                        .WithMany("StockOutDetails")
                        .HasForeignKey("StockOutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SOD_StockOut");

                    b.Navigation("Location");

                    b.Navigation("Product");

                    b.Navigation("StockOut");
                });

            modelBuilder.Entity("EWMS.Models.StockOutReceipt", b =>
                {
                    b.HasOne("EWMS.Models.User", "IssuedByNavigation")
                        .WithMany("StockOutReceipts")
                        .HasForeignKey("IssuedBy")
                        .IsRequired()
                        .HasConstraintName("FK_StockOut_IssuedBy");

                    b.HasOne("EWMS.Models.SalesOrder", "SalesOrder")
                        .WithMany("StockOutReceipts")
                        .HasForeignKey("SalesOrderId")
                        .HasConstraintName("FK_StockOut_SalesOrder");

                    b.HasOne("EWMS.Models.TransferRequest", "Transfer")
                        .WithMany("StockOutReceipts")
                        .HasForeignKey("TransferId")
                        .HasConstraintName("FK_StockOut_Transfer");

                    b.HasOne("EWMS.Models.Warehouse", "Warehouse")
                        .WithMany("StockOutReceipts")
                        .HasForeignKey("WarehouseId")
                        .IsRequired()
                        .HasConstraintName("FK_StockOut_Warehouse");

                    b.Navigation("IssuedByNavigation");

                    b.Navigation("SalesOrder");

                    b.Navigation("Transfer");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("EWMS.Models.TransferDetail", b =>
                {
                    b.HasOne("EWMS.Models.Product", "Product")
                        .WithMany("TransferDetails")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_TransferDetails_Product");

                    b.HasOne("EWMS.Models.TransferRequest", "Transfer")
                        .WithMany("TransferDetails")
                        .HasForeignKey("TransferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TransferDetails_Transfer");

                    b.Navigation("Product");

                    b.Navigation("Transfer");
                });

            modelBuilder.Entity("EWMS.Models.TransferRequest", b =>
                {
                    b.HasOne("EWMS.Models.User", "ApprovedByNavigation")
                        .WithMany("TransferRequestApprovedByNavigations")
                        .HasForeignKey("ApprovedBy")
                        .HasConstraintName("FK_TR_ApprovedBy");

                    b.HasOne("EWMS.Models.Location", "FromLocation")
                        .WithMany("TransferRequestFromLocations")
                        .HasForeignKey("FromLocationId");

                    b.HasOne("EWMS.Models.Warehouse", "FromWarehouse")
                        .WithMany("TransferRequestFromWarehouses")
                        .HasForeignKey("FromWarehouseId")
                        .IsRequired()
                        .HasConstraintName("FK_TR_FromWarehouse");

                    b.HasOne("EWMS.Models.User", "RequestedByNavigation")
                        .WithMany("TransferRequestRequestedByNavigations")
                        .HasForeignKey("RequestedBy")
                        .IsRequired()
                        .HasConstraintName("FK_TR_RequestedBy");

                    b.HasOne("EWMS.Models.Location", "ToLocation")
                        .WithMany("TransferRequestToLocations")
                        .HasForeignKey("ToLocationId");

                    b.HasOne("EWMS.Models.Warehouse", "ToWarehouse")
                        .WithMany("TransferRequestToWarehouses")
                        .HasForeignKey("ToWarehouseId")
                        .IsRequired()
                        .HasConstraintName("FK_TR_ToWarehouse");

                    b.Navigation("ApprovedByNavigation");

                    b.Navigation("FromLocation");

                    b.Navigation("FromWarehouse");

                    b.Navigation("RequestedByNavigation");

                    b.Navigation("ToLocation");

                    b.Navigation("ToWarehouse");
                });

            modelBuilder.Entity("EWMS.Models.User", b =>
                {
                    b.HasOne("EWMS.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_Users_Roles");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EWMS.Models.UserWarehouse", b =>
                {
                    b.HasOne("EWMS.Models.User", "User")
                        .WithMany("UserWarehouses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserWarehouses_Users");

                    b.HasOne("EWMS.Models.Warehouse", "Warehouse")
                        .WithMany("UserWarehouses")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserWarehouses_Warehouses");

                    b.Navigation("User");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("EWMS.Models.Location", b =>
                {
                    b.Navigation("Inventories");

                    b.Navigation("StockInDetails");

                    b.Navigation("StockOutDetails");

                    b.Navigation("TransferRequestFromLocations");

                    b.Navigation("TransferRequestToLocations");
                });

            modelBuilder.Entity("EWMS.Models.Product", b =>
                {
                    b.Navigation("Inventories");

                    b.Navigation("PurchaseOrderDetails");

                    b.Navigation("SalesOrderDetails");

                    b.Navigation("StockInDetails");

                    b.Navigation("StockOutDetails");

                    b.Navigation("TransferDetails");
                });

            modelBuilder.Entity("EWMS.Models.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("EWMS.Models.PurchaseOrder", b =>
                {
                    b.Navigation("PurchaseOrderDetails");

                    b.Navigation("StockInReceipts");
                });

            modelBuilder.Entity("EWMS.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("EWMS.Models.SalesOrder", b =>
                {
                    b.Navigation("SalesOrderDetails");

                    b.Navigation("StockOutReceipts");
                });

            modelBuilder.Entity("EWMS.Models.StockInReceipt", b =>
                {
                    b.Navigation("StockInDetails");
                });

            modelBuilder.Entity("EWMS.Models.StockOutReceipt", b =>
                {
                    b.Navigation("StockOutDetails");
                });

            modelBuilder.Entity("EWMS.Models.Supplier", b =>
                {
                    b.Navigation("ProductCategories");

                    b.Navigation("PurchaseOrders");
                });

            modelBuilder.Entity("EWMS.Models.TransferRequest", b =>
                {
                    b.Navigation("StockInReceipts");

                    b.Navigation("StockOutReceipts");

                    b.Navigation("TransferDetails");
                });

            modelBuilder.Entity("EWMS.Models.User", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("PurchaseOrders");

                    b.Navigation("SalesOrders");

                    b.Navigation("StockInReceipts");

                    b.Navigation("StockOutReceipts");

                    b.Navigation("TransferRequestApprovedByNavigations");

                    b.Navigation("TransferRequestRequestedByNavigations");

                    b.Navigation("UserWarehouses");
                });

            modelBuilder.Entity("EWMS.Models.Warehouse", b =>
                {
                    b.Navigation("Locations");

                    b.Navigation("PurchaseOrders");

                    b.Navigation("SalesOrders");

                    b.Navigation("StockInReceipts");

                    b.Navigation("StockOutReceipts");

                    b.Navigation("TransferRequestFromWarehouses");

                    b.Navigation("TransferRequestToWarehouses");

                    b.Navigation("UserWarehouses");
                });
#pragma warning restore 612, 618
        }
    }
}
